Edited code to print log messages
JIITODC/loadbalancer pull request #25
Opened 2022-11-15 14:22 UTC by elle-Bee

Made changes in the code to log errors if there is no container to forward to. Also created a function GetLabel() which checks if there is a container to forward. This check happens in the beginning of the program to save time.

2022-11-15 19:12 UTC, Shreyas220 requested changes
LGTM  :+1: 
just a few changes required 
#22 #21

2022-11-15 19:12 UTC, Shreyas220 commented on docker-lb/docker-handler/docker.go
> +	key := "com.docker-lb.load-balance"
can you remove this 
we just added this to test something not needed anymore

2022-11-15 19:12 UTC, Shreyas220 commented on docker-lb/docker-handler/docker.go
>  	if _, ok := labels[key]; !ok {
change Key to `dh.Docker.Label`

2022-11-16 02:05 UTC, elle-Bee commented on docker-lb/docker-handler/docker.go
> +	key := "com.docker-lb.load-balance"
Sure!

2022-11-16 02:11 UTC, elle-Bee commented on docker-lb/docker-handler/docker.go
>  	if _, ok := labels[key]; !ok {
Should I change it to dh.DockerHandler.Label because dh.Docker does not contain Label in it ?

2022-11-16 11:01 UTC, Shreyas220 commented on docker-lb/docker-handler/docker.go
>  	if _, ok := labels[key]; !ok {
no 
its a variable

2022-11-16 11:06 UTC, elle-Bee commented on docker-lb/docker-handler/docker.go
>  	if _, ok := labels[key]; !ok {
Ok I got confused. So it should be dh.DockerHandler.Label instead of dh.docker.Label right?

2022-11-16 11:32 UTC, Shreyas220 commented on docker-lb/docker-handler/docker.go
>  	if _, ok := labels[key]; !ok {
aah sorry 
it should be just   dh.Label

2022-11-17 17:29 UTC, Shreyas220 requested changes

2022-11-17 17:29 UTC, Shreyas220 commented on docker-lb/docker-handler/docker.go
> +	key := "dh.Label"
```suggestion

```

2022-11-17 17:29 UTC, Shreyas220 commented on docker-lb/docker-handler/docker.go
>  	if _, ok := labels[key]; !ok {
```suggestion
	if _, ok := labels[dh.Label]; !ok {
```

2022-11-17 17:30 UTC, Shreyas220 requested changes

2022-11-17 17:30 UTC, Shreyas220 commented on docker-lb/docker-handler/docker.go
>  	server.ServiceName = labels[key]
```suggestion
	server.ServiceName = labels[dh.Label]
```

2022-11-18 16:54 UTC, elle-Bee commented on docker-lb/docker-handler/docker.go
>  	server.ServiceName = labels[key]
Made the changes
Also in  `docker.go`, the key variable was redundant so deleted it too

2022-11-18 17:47 UTC, Shreyas220 approved these changes
Awesome!!
LGTM

2022-11-18 17:47 UTC, merged